environment:
  matrix:
    - TRAVIS_SMALLTALK_VERSION: Squeak-5.0
    - TRAVIS_SMALLTALK_VERSION: Pharo-5.0

platform:
  - x86

clone_depth: 5

build: false

# Cygwin build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
test_script:
  - cmd: c:\\cygwin\\bin\\bash -lc "cd $APPVEYOR_BUILD_FOLDER; exec 0</dev/null; ./run.sh"
