language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5

  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

os:
  - linux
  - osx

env:
  global:
    - BASELINE="SWTDemo"
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"

install:
  - wget -q -O fixtures.zip https://github.com/hpi-swa/smalltalkCI/archive/fixtures.zip
  - unzip -q fixtures.zip
  - export PROJECT_HOME="$(pwd)/smalltalkCI-fixtures"

# Include builds for builderCI fallback
matrix:
  include:
    - smalltalk: Squeak-4.4
      os: linux
      sudo: required
    - smalltalk: Squeak-4.3
      os: linux
      sudo: required

    - smalltalk: Pharo-2.0
      os: linux
      sudo: required
    - smalltalk: Pharo-1.4
      os: linux
      sudo: required
    - smalltalk: Pharo-1.2
      os: linux
      sudo: required
    - smalltalk: Pharo-1.1
      os: linux
      sudo: required
  
    - smalltalk: GemStone-3.2.7
      os: linux
      sudo: required
    - smalltalk: GemStone-3.2.0
      os: linux
      sudo: required
    - smalltalk: GemStone-3.1.0.6
      os: linux
      sudo: required
    - smalltalk: GemStone-3.1.0.2
      os: linux
      sudo: required
    - smalltalk: GemStone-3.0.1
      os: linux
      sudo: required
    - smalltalk: GemStone-2.4.6
      os: linux
      sudo: required
    - smalltalk: GemStone-2.4.5
      os: linux
      sudo: required
    - smalltalk: GemStone-2.4.4.1
      os: linux
      sudo: required
