language: smalltalk
sudo: false

baseline: SWTDemo

env:
  global:
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"

addons:
  apt:
    hosts:
      - travis.dev

install:
  - unset SMALLTALK_CI_HOME && source env_vars # make sure to use smalltalkCI from this branch
  - wget -q -O fixtures.zip https://github.com/hpi-swa/smalltalkCI/archive/fixtures.zip
  - unzip -q fixtures.zip
  - export PROJECT_HOME="$(pwd)/smalltalkCI-fixtures"

matrix:
  include:
    - language: generic
      script:
        - bash tests/run_tests.sh
        - bash tests/helpers_tests.sh
        - bash tests/pharo_tests.sh
        - bash tests/squeak_tests.sh

    - smalltalk: GemStone-3.2.12  # test with container
      os: linux
      sudo: required
    - smalltalk: GemStone-3.0.1   # test with builderCI
      os: linux
      sudo: required
      group: legacy
      env: BUILDERCI=true
  fast_finish: true

branches:
  except:
    - fixtures
