language: smalltalk
sudo: true

smalltalk:
#  - Squeak-trunk
##  - Squeak-5.0
##  - Squeak-4.6
##  - Squeak-4.5
#
##      - Pharo-alpha
##  - Pharo-stable
##  - Pharo-5.0
##  - Pharo-4.0
##  - Pharo-3.0

  - GemStone-3.2.12
#  - GemStone-3.1.0.6

os:
  - linux
  - osx

env:
  global:
    - BASELINE="SWTDemo"
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"

addons:
  hosts:
    - travis.dev

install:
  - unset SMALLTALK_CI_HOME && source env_vars # make sure to use smalltalkCI from this branch
  - wget -q -O fixtures.zip https://github.com/hpi-swa/smalltalkCI/archive/fixtures.zip
  - unzip -q fixtures.zip
  - export PROJECT_HOME="$(pwd)/smalltalkCI-fixtures"

matrix:
  include:
    # Bash tests
    - language: generic
      script:
        - bash tests/run_tests.sh
        - bash tests/helpers_tests.sh
        - bash tests/pharo_tests.sh
        - bash tests/squeak_tests.sh

#    # Legacy Squeak builds using builderCI
#    - smalltalk: Squeak-4.4
#      os: linux
#      sudo: required
#      group: legacy
#      env: BUILDERCI=true
#    # - smalltalk: Squeak-4.3
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    #   env: BUILDERCI=true
#
#    # Legacy Pharo builds using builderCI
#    - smalltalk: Pharo-2.0
#      os: linux
#      sudo: required
#      group: legacy
#      env: BUILDERCI=true
#    # - smalltalk: Pharo-1.4
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    #   env: BUILDERCI=true
#    # - smalltalk: PharoCore-1.2
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    #   env: BUILDERCI=true
#    # - smalltalk: PharoCore-1.1
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    #   env: BUILDERCI=true
#
#    # Legacy GemStone builds using builderCI
#    - smalltalk: GemStone-3.2.7
#      os: linux
#      sudo: required
#      group: legacy
#      env: BUILDERCI=true
#    # - smalltalk: GemStone-3.2.0
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    # - smalltalk: GemStone-3.1.0.5
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    # - smalltalk: GemStone-3.1.0
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    # - smalltalk: GemStone-3.0.1
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    # - smalltalk: GemStone-2.4.7
#    #   os: linux
#    #   sudo: required
#    #   group: legacy
#    # - smalltalk: GemStone-2.4.4.1
#    #   os: linux
#    #   sudo: required
#    :    #   group: legacy
  allow_failures:
    - smalltalk: Squeak-4.4
    - smalltalk: Squeak-4.3

    - smalltalk: Pharo-2.0
    - smalltalk: Pharo-1.4
    - smalltalk: PharoCore-1.2
    - smalltalk: PharoCore-1.1

    - smalltalk: GemStone-3.2.7
    - smalltalk: GemStone-3.2.0
    - smalltalk: GemStone-3.1.0.5
    - smalltalk: GemStone-3.1.0
    - smalltalk: GemStone-3.0.1
    - smalltalk: GemStone-2.4.7
    - smalltalk: GemStone-2.4.4.1
  fast_finish: true

branches:
  except:
    - fixtures
