language: smalltalk
sudo: false

smalltalk:
  - Squeak-trunk
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5

  - Pharo-alpha
  - Pharo-stable
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

  - GemStone-3.3.0
  - GemStone-3.2.12
  - GemStone-3.1.0.6

os:
  - linux
  - osx

install:
  - unset SMALLTALK_CI_HOME && source env_vars # make sure to use smalltalkCI from this branch

script:
  - $SMALLTALK_CI_HOME/run.sh --debug && $SMALLTALK_CI_HOME/tests/fail_test.sh

matrix:
  include:
    # Bash tests
    - language: bash
      smalltalk:
      sudo: false
      script: bash $SMALLTALK_CI_HOME/tests/all_tests.sh

  fast_finish: true

# Fully cached build for all supported platforms - 314MB cache
#cache:
#  directories:
#    - $TRAVIS_BUILD_DIR/_cache
