language: smalltalk
sudo: false

smalltalk: Pharo-5.0

os: osx
osx_image: xcode7

install:
  # Move cache directory if it exists
  - if [[ -d "${SMALLTALK_CI_CACHE}" ]]; then mv $SMALLTALK_CI_CACHE "$(pwd)"; fi
  # Make sure to use smalltalkCI from this branch
  - if [[ -n "${SMALLTALK_CI_HOME}" ]]; then rm -rf $SMALLTALK_CI_HOME && ln -s "$(pwd)" $SMALLTALK_CI_HOME && source $SMALLTALK_CI_HOME/env_vars; fi

script: $SMALLTALK_CI_HOME/run.sh --debug
