language: smalltalk
sudo: false

smalltalk:
  - Squeak-Trunk
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5

  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
  # - Pharo-2.0

os:
  - linux
  - osx

env:
  global:
    - BASELINE=SWTDemo

install:
  - wget -q -O fixtures.zip https://github.com/hpi-swa/filetreeCI/archive/fixtures.zip
  - unzip -q fixtures.zip
  - export PROJECT_HOME="$(pwd)/filetreeCI-fixtures"
