language: smalltalk
sudo: false

smalltalk:
#  - Squeak-trunk
  - Squeak-5.0
#  - Squeak-4.6
#  - Squeak-4.5
#
#  - Pharo-alpha
#  - Pharo-stable
  - Pharo-5.0
#  - Pharo-4.0
#  - Pharo-3.0

  - GemStone-3.3.0
  - GemStone-3.2.12
  - GemStone-3.1.0.6

os:
  - linux
  - osx

cache:
  directories:
  - _builds/travis/github-cache

install:
  - unset SMALLTALK_CI_HOME && source env_vars # make sure to use smalltalkCI from this branch

script: $SMALLTALK_CI_HOME/run.sh --debug

matrix:
  include:
    # Bash tests
    - language: generic
      sudo: false
      script: bash $SMALLTALK_CI_HOME/tests/all_tests.sh

  allow_failures:
    - smalltalk: Squeak-4.4
    - smalltalk: Squeak-4.3

    - smalltalk: Pharo-2.0
    - smalltalk: Pharo-1.4
    - smalltalk: PharoCore-1.2
    - smalltalk: PharoCore-1.1

  fast_finish: true

branches:
  except:
    - fixtures
