language: smalltalk
sudo: false

smalltalk:
  - Squeak-Trunk
  - Squeak-5.0
  - Squeak-4.6
  - Squeak-4.5

  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0
  # - Pharo-2.0

os:
  - linux
  - osx

env:
  - BASELINE=SWTDemo

install:
  - source env_vars
  - wget -q -O fixtures.zip https://github.com/hpi-swa/filetreeCI/archive/fixtures.zip
  - unzip -q fixtures.zip
  - export PROJECT_HOME="$(pwd)/filetreeCI-fixtures"

matrix:
  allow_failures:
    - smalltalk: Pharo-5.0
    - smalltalk: Pharo-4.0
    - smalltalk: Pharo-3.0
    - smalltalk: Pharo-2.0
